config/routes.rb
Rails.application.routes.draw do
  root 'categories#splash'
  devise_for :users
  resources :categories, only: %i[index show new create]
  resources :entities, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :entities

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :entities

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :redirect
  skip_before_action :redirect, only: [:splash]
  before_action :set_category, only: %i[show]

  def index
    @categories = Category.includes(:entities).all
  end

  def show
    @entities = @category.entities.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def splash
    redirect_to categories_path if user_signed_in?
  end

  private

  def redirect
    redirect_to root_path unless user_signed_in?
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @entity = Entity.new
  end

  def create
    @entity = current_user.entities.new(entity_params)
    if @entity.save
      redirect_to categories_path, notice: 'Entity was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/categories/_category.html.erb
<%if current_page?(categories_path)%>
<a href=<%=category_path(category.id) %>>
    <div class="categoryCard__index">
        <%= image_tag (category.icon), height: '90', width: '90'%>
        <p><%= category.name %></p>
        <p>$<%= category.entities.map {|entity| entity.amount}.sum %></p>
    </div>
</a>
<%else%>
    <div class="categoryCard_show">
        <p><%= category.name %></p>
        <p>$<%= category.entities.map {|entity| entity.amount}.sum %></p>
    </div>
<%end%>

app/views/categories/_entity.html.erb
<div class="entity">
    <p><%= entity.name %></p>
    <p><%= entity.created_at.to_fs(:db)[0..9]%></p>
    <p>$<%= entity.amount %></p>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, class: "newCategory__form" do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label :icon %>
  <%= form.url_field :icon %>
</div>
  <div class="newCategory__form-buttonDiv">
    <%= form.submit "CREATE CATEGORY", class:"newCategory__form-button" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section class="categories">

  <div class="categories__list">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>

  <div class="divButton">
    <%= button_to "NEW CATEGORY", new_category_path, method: :get, class: "bottomButton" %>
  </div>
</section>

app/views/categories/new.html.erb
<section class="newCategory">
  <h1>New category</h1>

  <%= render "form", category: @category %>
</section>

app/views/categories/show.html.erb
<%= render @category %>
<div class="entityList">
  <% @entities.each do |entity| %>
    <%= render "entity", entity: entity %>
  <% end %>
</div>

<div class="divButton">
  <%= button_to "Add a new transaction", new_entity_path, method: :get, class: "bottomButton" %>
</div>

app/views/categories/splash.html.erb
<section class="splash">
<%= image_tag "budgeyLogo.png", height: 150, width: 150, :style => "margin: 0 auto" %>
<div>
    <%= button_to "LOG IN", new_user_session_path, class: "splash__LogIn", method: :get%>
    <%= button_to "SIGN UP", new_user_registration_path, class: "splash__SignUp", method: :get%>
</div>
</section>

app/views/entities/_form.html.erb
<%= form_with model: entity, url: entities_path, class:"newEntity__form" do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount, step: 0.01  %>
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>

  <div class="newEntity__form-buttonDiv">
    <%= form.submit "Save", class:"newEntity__form-button" %>
  </div>
<% end %>

app/views/entities/new.html.erb
<section class="newEntity">
  <h1>New entity</h1>
  <%= render "form", entity: @entity %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="desktop-only">
      <h1>Sorry! We are working in the desktop version. Try by looging through your phone. </h1>
    </div>
    <div class="mobile-only">
      <%= render "shared/navbar" unless current_page?("/") %> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
      <div class="navbar-container container">
          <% if current_page?(categories_path) %>
          <input type="checkbox" name="" id="">
          <div class="hamburger-lines">
              <span class="line line1"></span>
              <span class="line line2"></span>
              <span class="line line3"></span>
          </div>
          <ul class="menu-items">
              <li class="menu-items__User">
                <%= image_tag "user.png",  height: 70, width: 70 %>
                <p><%= current_user.name %></p>
              </li>
              <li><a href="/categories">CATEGORIES</a></li>
              <li><a href="/categories/new">NEW CATEGORY</a></li>
              <li><a href="/entities/new">NEW ENTITY</a></li>
              <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "signOut_button" %></li>
          </ul>
            <% else %>
                <%= link_to '<', :back, class: "navbar__BackButton" %>
            <% end %>
          <a href="/"><h1 class="logo">BUDGEY</h1></a>
      </div>
  </nav>